# Add this service to your docker-compose.yml (or run separately)
keycloak:
  image: quay.io/keycloak/keycloak:25.0.1
  command: start-dev --http-port=8081 --import-realm
  environment:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
  ports:
    - "8081:8081"
  volumes:
    - ./keycloak/realms:/opt/keycloak/data/import
