server:
  port: 9005
spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=finance;encrypt=false;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.default_schema: budget
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history_budget
    default-schema: budget
    schemas: budget
    baseline-on-migrate: true
    baseline-version: 0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/finance

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
